[package]
name = "app"
version = "0.1.0"
authors = ["aoki <ringohub@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oorandom = "11.1.2"
my_lib = {path = "my_lib"}
